### PR TITLE
fix(dataplan-pg): type restrictions

### LINKED ISSUE #1755: Broken type helper (GetPgResourceRelations)
### Summary

Various type helpers appear to be broken (`GetPgResourceRelations`) for example always returns `any` even when supplying a fully typed `PgResource` with explicit relations. I would advice to use `infer` instead of property access to prevent type erasure.

Below works:

```typescript
type GetRegistry<U> = U extends PgResource<any, any, any, any, infer R>
  ? R
  : never
type GetRelations<U> = U extends PgRegistry<any, any, infer R> ? R : never
type GetCodec<U> = U extends PgResource<any, infer C, any, any, any>
  ? C
  : never
type GetName<U> = U extends PgCodec<infer N, any, any, any, any, any, any>
  ? N
  : never
type GetPgResourceRelations<U> = U extends PgResource<
  any,
  any,
  any,
  any,
  any
>
  ? GetRelations<GetRegistry<U>>[GetName<GetCodec<U>>]
  : never
```

Whereas this doesnt:

```typescript
type GetPgResourceRelations<TResource extends PgResource<any, any, any, any, any>> = TResource["registry"]["pgRelations"][TResource["codec"]["name"]];
```

### PR DESCRIPTION
**Pull request by wesselvdv**
## Description

fixes #1755 

## Checklist

- [ ] My code matches the project's code style and `yarn lint:fix` passes.
- [ ] I've added tests for the new feature, and `yarn test` passes.
- [ ] I have detailed the new feature in the relevant documentation.
- [ ] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
- [ ] If this is a breaking change I've explained why.

### CODE REVIEW

**Comment by wesselvdv** [comment]
Applying this fix allows you to get actual type completion on a typed `PgSelectStep<A>` for `singleRelation` where the input of `singleRelation` is only valid if it exists as a relation in the associated `PgRegistry` for type `A`

**Comment by benjie** [comment]
Doesn't this _reduce_ type safety by removing the constraints on the generics though?

**Comment by wesselvdv** [comment]
That's true, but the current constraints are too strict causing it to not be workable. I can't pass a object that can satisfy the constraints without causing it to be useless because I have to union `"asd"` with `string` keys causing it to be generic again.

**Comment by wesselvdv** [comment]
I also see that the use of `undefined` as bottom type is problematic in many cases, I think it's better to use `never` in such cases. And you don't need to explicitly indicate that it might be `never` in a union.

**Comment by benjie** [comment]
... but it's not "never" - it's literally that those things can be undefined. A function accepts an array of parameters (even an empty array), a table does _not_ accept an array of parameters - the parameters are undefined - we should be able to differentiate this at a type level, otherwise we can't tell the difference between function-like and table-like... can we?

:thinking: _Thinking pause..._

Maybe you're right... a table "never" accepts parameters... It's a bit weird because `foo 
 never = foo` for all `foo`... but I think we can still check it:

https://www.typescriptlang.org/play?#code/C4TwDgpgBAYlC8UB2BXAtgIwgJygH2QgDccBuAKAHpKpaA9AfnNEigHEFYoIAPYCJABMAzoRK4GUYNhTQAXFABmAQwA2wiBWq0ojZuGgAJTkmJkqNekxbQAkp2O9+Q0afFRJ02VAUr1mix09IA

My main concern is that this might look confusing to the consumer - they might think parameters is _always_ required (since `| never` evaporates) and thus pass an empty array when they should be passing `never`. Currently the `| undefined` is very explicit that that's an option. Having said that, if it makes working with the types easier and doesn't actually break anything, I'm open to it.

**Comment by benjie** [comment]
Is it the `[name in string]` causing the issues for you; would `[name: string]` be any better? I'm not sufficiently knowledgeable about TypeScript to fully understand the difference.

**Comment by wesselvdv** [comment]
> Is it the `[name in string]` causing the issues for you; would `[name: string]` be any better? I'm not sufficiently knowledgeable about TypeScript to fully understand the difference.

I am playing around with another one:

```typescript
export interface PgRegistry<
  TCodecs extends Record<
    keyof TCodecs,
    PgCodec<any, PgCodecAttributes, any, any, any, any, any>
  >,
  TResourceOptions extends Record<
    keyof TResourceOptions,
    PgResourceOptions<
      string,
      TCodecs[keyof TCodecs],
      ReadonlyArray<PgResourceUnique<PgCodecAttributes>>,
      ReadonlyArray<PgResourceParameter>
    >
  >,
  TRelations extends Record<
    keyof TRelations,
    Record<
      keyof TRelations[keyof TRelations],
      PgCodecRelationConfig<
        any,
        PgCodec<string, PgCodecAttributes, any, any, never, any, never>,
        PgResourceOptions<any, PgCodecWithAttributes<any>, any, any>
      >
    >
  >,
> {
  pgCodecs: TCodecs
  pgResources: {
    [name in keyof TResourceOptions]: TResourceOptions[name] extends PgResourceOptions<
      infer UName,
      infer UCodec,
      infer UUniques,
      infer UParameters
    >
      ? PgResource<
          UName,
          UCodec,
          UUniques,
          UParameters,
          PgRegistry<TCodecs, TResourceOptions, TRelations>
        >
      : never
  }
  pgRelations: {
    [codecName in keyof TRelations]: {
      [relationName in keyof TRelations[codecName]]: Expand<
        Omit<TRelations[codecName][relationName], "remoteResourceOptions"> & {
          remoteResource: TRelations[codecName][relationName] extends {
            remoteResourceOptions: PgResourceOptions<
              infer UName,
              infer UCodec,
              infer UUniques,
              infer UParameters
            >
          }
            ? PgResource<
                UName,
                UCodec,
                UUniques,
                UParameters,
                PgRegistry<TCodecs, TResourceOptions, TRelations>
              >
            : never
        }
      >
    }
  }
}
```

**Comment by benjie** [comment]
`Foo extends Record<keyof Foo, ...>`

But the... wait the key... the... of... of the... ... what?! :exploding_head:

**Comment by benjie** [comment]
I appreciate your work on this @wesselvdv; I'm going to convert this PR to a "draft" to indicate that research is still in progress. You can probably see I tried a bunch of approaches and the current one is the best I could come up with, but I still very much do not like it, and it requires too much manual `as ...` casting - not to mention not accepting perfectly valid things that it should accept.

**Comment by wesselvdv** [comment]
> I appreciate your work on this @wesselvdv; I'm going to convert this PR to a "draft" to indicate that research is still in progress. You can probably see I tried a bunch of approaches and the current one is the best I could come up with, but I still very much do not like it, and it requires too much manual `as ...` casting - not to mention not accepting perfectly valid things that it should accept.

I closed this one in favour for my other branch, for which I have created a new PR.https://github.com/graphile/crystal/pull/1784

**Pull request closed without merging**
