### PR TITLE
Docs fixes

### PR DESCRIPTION
**Pull request by Pascualex**
Small fixes to the docs as I go through them

### CODE REVIEW

**Review by benjie — APPROVED** [review]
Thanks!

**Comment by benjie** [comment]
Feel free to continue submitting more fixes through future PRs :+1:

**Comment by benjie** [comment]
In future, please check the checkbox to allow edits from maintainers - this may require that you make your changes to a branch that isn't your `main` branch. The fix you applied above means that code block is now valid, which means `prettier` wants to format it. (`yarn lint:fix` solves, but I've done that locally but cannot push to your branch.)

**Comment by Pascualex** [comment]
Great I'll take that into account for future PRs!

**Pull request merged**
